### ISSUE TITLE
Fail to complete trace with stat64 and write

### ISSUE THREAD

**Issue by AnoopNadig** [pkmoore/rrapper#81] opened 2018-12-04 20:07 UTC
When testing for the tool 'iostat' normal rreplay, i.e. without changing anything in any of the system calls, fails to execute and gives the 'openat(295) is not from trace:write' error. Here's the entire output:
```
DEBUG:root:No debug printer associated with syscall_id
Traceback (most recent call last):
  File "build/bdist.linux-i686/egg/src/inject.py", line 577, in main
    syscallreplay.entering_syscall)
  File "build/bdist.linux-i686/egg/src/inject.py", line 153, in debug_handle_syscall
    handle_syscall(pid, syscall_id, syscall_object, entering)
  File "build/bdist.linux-i686/egg/src/inject.py", line 214, in handle_syscall
    util.validate_syscall(syscall_id, syscall_object)
  File "/home/alex/rrapper/crashsim/local/lib/python2.7/site-packages/syscallreplay/util.py", line 221, in validate_syscall
    syscall_object.name))
ReplayDeltaError: System call validation failed: from execution: openat(295) is not from trace:write
Failed to complete trace
Injector for event:rec_pid 291:1961 failed
```
My trace file contains a stat64() call followed by a write() call. Here are the contents of my trace_snip.strace file:
```
1961  stat64("/etc/localtime", {st_dev=makedev(8, 1), st_ino=2230664, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=2845, st_atime=1543880662 /* 2018-12-03T15:44:22.068026113-0800 */, st_atime_nsec=68026113, st_mtime=1540806663 /* 2018-10-29T02:51:03-0700 */, st_mtime_nsec=0, st_ctime=1542057997 /* 2018-11-12T13:26:37.065961269-0800 */, st_ctime_nsec=65961269}) = 0
1961  write(1, "", 0)                   = 0
```

**Comment by pkmoore** [comment] 2018-12-04 23:05
I believe this is a duplicate of #70

**Closed by pkmoore** 2018-12-04 23:05 UTC
